name: gclass
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  gclass_annotation:
    path: ../gclass_annotation
  analyzer: '>=5.12.0 <7.0.0'
  build: ^2.4.1
  build_runner: ^2.4.7
  source_gen: ^1.4.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0
  build_test: any
